package jp.co.geisha.itunestracker.service.model

data class Artist (
    var wrapperType: String,
    var kind: String,
    var artistId: Int = 0,
    var collectionId: Int = 0,
    var trackId: Int = 0,
    var artistName: String,
    var collectionName: String,
    var trackName: String,
    var collectionCensoredName: String,
    var trackCensoredName: String,
    var artistViewUrl: String,
    var collectionViewUrl: String,
    var trackViewUrl: String,
    var previewUrl: String,
    var artworkUrl30: String,
    var artworkUrl60: String,
    var artworkUrl100: String,
    var collectionPrice: Float,
    var trackPrice: Float,
    var releaseDate: String,
    var collectionExplicitness: String,
    var discCount: Int,
    var discNumber: Int,
    var trackCount: Int,
    var trackNumber: Int,
    var trackTimeMillis: Int,
    var country: String,
    var currency: String,
    var primaryGenreName: String
)
